// SEO title overrides per product slug — used to break up duplicate <title>
// tags on product pages that share the same product.title in Strapi.
// If a slug isn't in this map, the auto-generated `${product.title} купить в Беларуси`
// is used.
export const PRODUCT_TITLE_OVERRIDES: Record<string, string> = {
    'kartochka-happy-birthday-2': 'Поздравительная открытка Happy Birthday — купить в Беларуси',
    'hapy_birthday_cards': 'Открытка Happy Birthday: стильное поздравление',
    'kartochka-happy-birthday': 'Карточка «Happy Birthday!» купить в Беларуси',
    'kartochka-happy-birthday-1': 'Поздравительная карточка Happy Birthday — заказать онлайн',
    'hhappy_birtday_cat': 'Открытка с котиком «Happy Birthday» — милый подарок на День рождения',
    'kartochka-dlya-tebya-3': 'Карточка «Для тебя» купить в Беларуси',
    'kartochka-dlya-tebya-1': 'Карточка «Для тебя» — купить стильную открытку с любовью',
    'kartochka-zagaday-zhelanie': 'Карточка «Загадай желание!» купить в Беларуси',
    'kartochka-zagaday-zhelanie-1': 'Открытка «Загадай желание!» купить в Беларуси',
    'kartochka-k-uspehu': 'Карточка «К успеху» купить в Беларуси',
    'kartochka-k-uspehu-1': 'Открытка «К успеху» купить в Беларуси',
    'kartochka-luchshemu-pape-na-svete-1': 'Открытка «Лучшему папе на свете»: заказать онлайн',
    'kartochka-luchshemu-pape-na-svete': 'Карточка «Лучшему папе на свете!» купить в Беларуси',
    'kartochka-lyubimomu-pape-1': 'Открытка «Любимому папе» — заказать в mppshop',
    'kartochka-lyubimomu-pape': 'Карточка «Любимому папе!» купить в Беларуси',
    'kartochka-ot-vsego-serdtsa': 'Карточка «От всего сердца» купить в Беларуси',
    'kartochka-ot-vsego-serdtsa-2': 'Подарочная открытка «От всего сердца» №2 — заказать в Беларуси',
    'kartochka-ot-vsego-serdtsa-1': 'Открытка «От всего сердца» №1: заказать онлайн',
    'kartochka-pozdravlyayu-1': 'Мини-карточка «Поздравляю!» — заказать в mppshop',
    'kartochka-pozdravlyayu': 'Карточка «Поздравляю!» купить в Беларуси',
    'kartochka-s-dnyom-rozhdeniya': 'Карточка «С Днём Рождения!» купить в Беларуси',
    'kartochka-s-dnyom-rozhdeniya-2': 'Карточка «С Днём Рождения!» №2 купить в Беларуси',
    'kartochka-s-novym-godom-2': 'Новогодняя открытка «С Новым годом!» — праздничный дизайн №2',
    'kartochka-s-novym-godom-1': 'Открытка «С Новым годом» — закажите сказочное настроение',
    'kartochka-samoy-krasivoy-2': 'Открытка «Самой красивой»: заказать в Беларуси',
    'kartochka-samoy-krasivoy-1': 'Карточка «Самой красивой» №1: заказать онлайн',
    'kartochka-samoy-krasivoy': 'Карточка «Самой красивой» купить в Беларуси',
    'kartochka-schastlivyh-prazdnikov-1': 'Праздничная карточка «Счастливых праздников!» — заказать в mppshop',
    'kartochka-schastlivyh-prazdnikov': 'Карточка «Счастливых праздников!» купить в Беларуси',
    'kartochka-ty-luchshaya': 'Карточка «Ты лучшая» купить в Беларуси',
    'kartochka-ty-luchshaya-1': 'Купить открытку «Ты лучшая» — заказать оригинальный подарок в mppshop',
    'kartochka-ty-sila-1': 'Открытка «Ты — сила!» купить по выгодной цене',
    'kartochka-ty-sila': 'Карточка «Ты — сила» купить в Беларуси',
    'stiker-s-prazdnikom-2': 'Стикер «С праздником!» №2 купить — заказать декор для подарков',
    'stiker-s-prazdnikom-2-1': 'Купить наклейку «С праздником!» — заказать стикеры для упаковки подарков',
}
