// H1 overrides per product slug — used to break up duplicate <h1> tags
// on product pages that share the same product.title in Strapi.
// Only the visible H1 is overridden; product.title is still used everywhere
// else (image alts, cart, similar-products blocks) as the canonical name.
export const PRODUCT_H1_OVERRIDES: Record<string, string> = {
    'kartochka-happy-birthday-2': 'Поздравительная открытка «Happy Birthday» №2',
    'hapy_birthday_cards': 'Набор дизайнерских открыток «Happy Birthday»',
    'kartochka-happy-birthday': 'Открытка «Happy Birthday» в классическом стиле',
    'kartochka-happy-birthday-1': 'Карточка «Happy Birthday» — праздничный дизайн',
    'hhappy_birtday_cat': 'Открытка «Happy Birthday» с милым котиком',
    'kartochka-dlya-tebya-3': 'Подарочная карточка «Для тебя»',
    'kartochka-dlya-tebya-1': 'Нежная открытка-карточка «Для тебя»',
    'kartochka-zagaday-zhelanie': 'Открытка «Загадай желание!» — для исполнения мечты',
    'kartochka-zagaday-zhelanie-1': 'Поздравительная карточка «Загадай желание!»',
    'kartochka-k-uspehu': 'Мотивационная открытка «К успеху»',
    'kartochka-k-uspehu-1': 'Стильная карточка «К успеху»',
    'kartochka-luchshemu-pape-na-svete-1': 'Открытка «Лучшему папе на свете!» — подарочная серия',
    'kartochka-luchshemu-pape-na-svete': 'Праздничная карточка «Лучшему папе на свете!»',
    'kartochka-lyubimomu-pape-1': 'Трогательная открытка «Любимому папе!»',
    'kartochka-lyubimomu-pape': 'Карточка «Любимому папе!» — лучший подарок',
    'iloveyouclassic': 'Мини-открытка «Люблю» (классика)',
    'iloveyoucard2': 'Дизайнерская карточка «Люблю»',
    'kartochka-ot-vsego-serdtsa': 'Искренняя открытка «От всего сердца»',
    'kartochka-ot-vsego-serdtsa-2': 'Подарочная карточка «От всего сердца»',
    'kartochka-ot-vsego-serdtsa-1': 'Карточка с пожеланием «От всего сердца»',
    'kartochka-pozdravlyayu-1': 'Универсальная открытка «Поздравляю!»',
    'kartochka-pozdravlyayu': 'Поздравительная карточка «Поздравляю!» с красивым декором',
    'kartochka-s-dnyom-rozhdeniya': 'Подарочная открытка «С Днём Рождения!»',
    'kartochka-s-dnyom-rozhdeniya-2': 'Карточка «С Днём Рождения!»',
    'kartochka-s-novym-godom-2': 'Новогодняя открытка «С Новым годом»',
    'kartochka-s-novym-godom-1': 'Праздничная карточка «С Новым годом»',
    'kartochka-samoy-krasivoy-2': 'Открытка «Самой красивой» №2',
    'kartochka-samoy-krasivoy-1': 'Поздравительная карточка «Самой красивой»',
    'kartochka-samoy-krasivoy': 'Изящная открытка «Самой красивой»',
    'kartochka-svetloy-pashi-s-teplom': 'Открытка «Светлой Пасхи!» с тёплыми пожеланиями',
    'brighteaster': 'Праздничная карточка «Светлой Пасхи!»',
    'kartochka-schastlivyh-prazdnikov-1': 'Праздничная карточка «Счастливых праздников!»',
    'kartochka-schastlivyh-prazdnikov': 'Открытка «Счастливых праздников!»',
    'kartochka-ty-luchshaya': 'Открытка «Ты лучшая!» для близкого человека',
    'kartochka-ty-luchshaya-1': 'Поздравительная карточка «Ты лучшая»',
    'kartochka-ty-sila-1': 'Мотивационная карточка «Ты — сила»',
    'kartochka-ty-sila': 'Дизайнерская открытка «Ты — сила»',
    'stiker-s-prazdnikom-2': 'Декоративный стикер «С праздником!» №2',
    'stiker-s-prazdnikom-2-1': 'Наклейка-стикер «С праздником!» для упаковки подарков',
}
